<?php


function autoloader($path)
{
	$path = str_replace('\\','/',$path);
	$path = $path.'.php';
	require_once $path;
}
spl_autoload_register('autoloader');


// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitae154b574d2d0dadba122808cce61cd3::getLoader();
